### ISSUE TITLE
Regarding the division of the dataset, especially the 1% scenario.

### ISSUE THREAD

**Issue by ShiverK** [charlesyou999648/ARCO#1]
Hello, I'm truly impressed by your work. I would like to inquire if you could provide the data splits for the 1%, 3%, and 5% data scenario. Additionally, I'm very interested in the weights of the model compared in the paper for the 1% data situation. Would you be willing to share that if it's convenient for you?

**Comment by charlesyou999648** [comment]
Hi, thanks for your interest! I have uploaded the splitting detailed to the repo.
