### ISSUE TITLE
Question about data preprocess detail

### ISSUE THREAD

**Issue by weihuang-cs** [charlesyou999648/ARCO#2]
Hello, you have done a great job in the field of semi-supervised segmentation with methods like Action and ARCO. I would like to reproduce your results on several datasets and I'm particularly interested in how the Lits dataset is processed into slices. Could you provide a script or preprocessed data for this purpose?

**Comment by charlesyou999648** [comment]
Thank you for your interest! Please check this sample code [https://github.com/charlesyou999648/ARCO/blob/03f6a893698cdb67a1a3560eb546e0678cf6385c/code/dataset/med_preprocessing.py](url).
